### ISSUE TITLE
Build failure starting with riscv-pk

### ISSUE THREAD

**Issue by tommythorn** [riscv/riscv-tools#9]
I haven't triage this yet, but want to bring attention to it.  With a clean pull of

```
commit 95f0b55eac15921f2133630bc6748131d8f1c0af
Author: Yunsup Lee <yunsup@cs.berkeley.edu>
Date:   Tue Feb 17 14:36:50 2015 -0800

    sync up riscv-tools
```

and a vanilla build on OSX 10.10.3 (`CC=gcc-4.8 CXX=g++-4.8 ./build.sh`), my build fails starting with `riscv-pk`:

```
Installing project riscv-gnu-toolchain

Configuring project riscv-pk
Building project riscv-pk
In file included from ../pk/frontend.c:4:0:
../pk/atomic.h: In function 'spinlock_lock_irqsave':
../pk/atomic.h:77:3: warning: implicit declaration of function 'clear_csr' [-Wimplicit-function-declaration]
   long flags = clear_csr(status, SR_EI);
   ^
../pk/atomic.h:77:26: error: 'status' undeclared (first use in this function)
   long flags = clear_csr(status, SR_EI);
                          ^
../pk/atomic.h:77:26: note: each undeclared identifier is reported only once for each function it appears in
../pk/atomic.h: In function 'spinlock_unlock_irqrestore':
../pk/atomic.h:85:3: warning: implicit declaration of function 'set_csr' [-Wimplicit-function-declaration]
   set_csr(status, flags & SR_EI);
   ^
../pk/atomic.h:85:11: error: 'status' undeclared (first use in this function)
   set_csr(status, flags & SR_EI);
           ^
../pk/fp.c: In function 'emulate_fp':
../pk/frontend.c: In function 'frontend_syscall':
../pk/frontend.c:26:3: warning: implicit declaration of function 'write_csr' [-Wimplicit-function-declaration]
   write_csr(tohost, magic_mem);
   ^
../pk/frontend.c:26:13: error: 'tohost' undeclared (first use in this function)
   write_csr(tohost, magic_mem);
             ^
../pk/frontend.c:27:3: warning: implicit declaration of function 'swap_csr' [-Wimplicit-function-declaration]
   while (swap_csr(fromhost, 0) == 0);
   ^
```
...

Other than that, the tools that installed appears to work.

**Comment by aswaterman** [comment]
On Wed, Jun 3, 2015 at 12:11 AM, Tommy Thorn <notifications@github.com>
wrote:

> I haven't triage this yet, but want to bring attention to it. With a clean
> pull of
>
> commit 95f0b55eac15921f2133630bc6748131d8f1c0af
> Author: Yunsup Lee <yunsup@cs.berkeley.edu>
> Date:   Tue Feb 17 14:36:50 2015 -0800
>
>     sync up riscv-tools
>
> and a vanilla build on OSX 10.10.3 (CC=gcc-4.8 CXX=g++-4.8 ./build.sh),
> my build fails starting with riscv-pk:
>

CC= CXX= is the problem.  It's forcing the proxy kernel to be built with
your host compiler.  There are a few workarounds, including editing
build.sh to prefix only a subset of the commands this way.

The upstream version's documentation doesn't suggest this approach anymore,
because it's clearly broken.

Installing project riscv-gnu-toolchain
